"use client";

import { useCallback, useEffect, useRef, useState, type ReactNode } from "react";

/**
 * The How it works tour: a ~1:15 "video" drawn in code (real type, real colors,
 * light/dark aware) with an optional voiceover: one continuous take by Lara
 * (ElevenLabs, natural and engaging), public/tour/tour.mp3. Nothing moves until someone
 * presses play, and sound only plays if they choose it. Scrub, skip 10s, jump by
 * chapter, captions on/off. It pauses when scrolled away and rests on the last
 * frame when done. Scenes read `lt` (ms into the chapter) and flip classes at
 * beats; CSS transitions do the motion.
 */

/** Where each line starts in tour.mp3 (s), from ElevenLabs word timestamps. Generated by record_tour.py. */
const LINE_AT = [0.05, 7.38, 19.89, 28.36, 33.87, 39.84, 44.36, 50.86, 61.96, 70.45, 80.12];
const AUDIO_END = 87.32;
/** Chapters open a beat before their line, so the picture lands as she starts speaking. */
const LEAD = 250;
/** Chapters held a little past their line, so the previous scene can be read (ms). */
const HOLD: Record<number, number> = {"10": 1000};
const START = LINE_AT.map((s, i) => (i === 0 ? 0 : Math.round(s * 1000) - LEAD + (HOLD[i] ?? 0)));
const TOTAL = Math.round(AUDIO_END * 1000) + 1500;
const DUR = START.map((s, i) => (START[i + 1] ?? TOTAL) - s);
/** In-chapter beats tied to words (s after the line starts). */
const BEATS = {
  pay: 1.65, // "Each share pays a dollar"
  profit: 3.87, // "Buy at forty-three cents"
  pct: 8.07, // "The price is also the crowd's odds"
  us: 5.35, // "plus one hundred thirty-three"
  mail: 3.49, // "Sign up for The Daily…"
  srch: 2.28, // "Search all of Polymarket…"
  askhp: 4.62, // "or ask HedgePredict…"
  conn: 0.58, // "connect HedgePredict…"
  apps: 3.16, // "or any AI tool…"
  paste: 6.42, // "Paste one link…"
  ask: 7.43, // "then just ask…"
};
const beat = (k: keyof typeof BEATS) => Math.round(BEATS[k] * 1000) + LEAD;
/** Captions, YouTube-style: one short phrase at a time, each shown from when she starts saying it (s). */
const CAPS: [number, string][] = [
  [0.05, "Hi! Welcome to HedgePredict."],
  [2.1, "We check the top markets on Polymarket"],
  [4.21, "and point out where there could be true value."],
  [7.38, "New to prediction markets?"],
  [9.03, "Each share pays $1 if you're right."],
  [11.25, "Buy at 43¢ and win, and that's 57¢ profit."],
  [15.45, "The price is also the crowd's odds: about 43%."],
  [19.89, "More familiar with sportsbook odds?"],
  [22.32, "Flip the switch at the top,"],
  [23.81, "and 43¢ becomes +133."],
  [28.36, "Here's the board:"],
  [29.69, "every market, its price, and HedgePredict's call."],
  [33.87, "Every market gets one of three calls."],
  [36.49, "The color shows HedgePredict's recommendation."],
  [39.84, "Each call says how sure it is,"],
  [41.65, "so you know how hard to lean on it."],
  [44.36, "Already holding a bet?"],
  [46.91, "Hedge Lab shows how to lock in a result, either way."],
  [50.86, "Want the best pick without checking the board?"],
  [54.35, "Sign up for The Daily, our free newsletter."],
  [57.09, "It sends the day's top pick to your inbox,"],
  [59.33, "weekday mornings."],
  [61.96, "Don't see your pick on the board?"],
  [64.24, "Search all of Polymarket from the search bar,"],
  [66.58, "or ask HedgePredict anything about any market."],
  [70.45, "You can also connect HedgePredict to Claude, ChatGPT,"],
  [73.61, "or any AI tool through our MCP."],
  [76.87, "Paste one link,"],
  [77.88, "then just ask."],
  [80.12, "So that's HedgePredict:"],
  [81.42, "you bring the plan,"],
  [82.34, "and we'll help you spot the value the market might be missing."],
  [85.37, "Play smart, and go get 'em!"],
];

type SceneProps = { lt: number };
const CHAPTERS: { tab: string; Scene: (p: SceneProps) => ReactNode }[] = [
  { tab: "Hi", Scene: Hello },
  { tab: "Prices", Scene: Prices },
  { tab: "Odds", Scene: Odds },
  { tab: "The board", Scene: Board },
  { tab: "Calls", Scene: Calls },
  { tab: "How sure", Scene: Sure },
  { tab: "Hedge Lab", Scene: Hedge },
  { tab: "The Daily", Scene: Daily },
  { tab: "Search & Ask", Scene: SearchAsk },
  { tab: "Connect AI", Scene: Ai },
  { tab: "That's it", Scene: End },
];
/** Where each chapter starts (ms), for links that jump into the tour. */
export const TOUR_AT = Object.fromEntries(CHAPTERS.map((c, i) => [c.tab, START[i]])) as Record<string, number>;
/** Ask the tour to play from a chapter (e.g. from the text version below it). */
export const playTourAt = (tab: string) => window.dispatchEvent(new CustomEvent("hp-tour-play", { detail: tab }));
const chapterAt = (t: number) => Math.max(0, START.findLastIndex((s) => t >= s));
const CC_KEY = "hp_tour_cc";
const mmss = (ms: number) => {
  const s = Math.round(ms / 1000);
  return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, "0")}`;
};

export function TourPlayer() {
  const [t, setT] = useState(0);
  const [playing, setPlaying] = useState(false);
  const [started, setStarted] = useState(false);
  const [sound, setSound] = useState(false);
  const box = useRef<HTMLDivElement>(null);
  const last = useRef<number | null>(null);
  const tRef = useRef(0);
  const audio = useRef<HTMLAudioElement | null>(null);
  const [cc, setCc] = useState(true);
  // Captions: on by default, remembered per browser.
  useEffect(() => {
    try {
      if (localStorage.getItem(CC_KEY) === "0") {
        const id = setTimeout(() => setCc(false), 0);
        return () => clearTimeout(id);
      }
    } catch {
      /* default on */
    }
  }, []);
  const toggleCc = () =>
    setCc((v) => {
      try {
        localStorage.setItem(CC_KEY, v ? "0" : "1");
      } catch {
        /* not remembered */
      }
      return !v;
    });

  // The clock: advance only while playing; stop on the last frame.
  useEffect(() => {
    if (!playing) return;
    let raf = 0;
    const tick = (now: number) => {
      const dt = last.current == null ? 0 : now - last.current;
      last.current = now;
      // With the voice playing, its clock is the clock (no drift); otherwise count frames.
      const a = audio.current;
      const heard = a && !a.paused && !a.ended ? a.currentTime * 1000 : null;
      setT((cur) => {
        const next = Math.min(TOTAL, heard ?? cur + dt);
        if (next >= TOTAL) setPlaying(false);
        return next;
      });
      raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => {
      cancelAnimationFrame(raf);
      last.current = null;
    };
  }, [playing]);

  // Scrolled out of view: pause (it never plays unseen).
  useEffect(() => {
    const el = box.current;
    if (!el) return;
    const io = new IntersectionObserver(([e]) => !e.isIntersecting && setPlaying(false), { threshold: 0.25 });
    io.observe(el);
    return () => io.disconnect();
  }, []);

  const toggle = useCallback(() => {
    setStarted(true);
    if (t >= TOTAL) {
      setT(0);
      if (audio.current) audio.current.currentTime = 0;
    }
    setPlaying((p) => !p || t >= TOTAL);
  }, [t]);
  const start = (withSound: boolean) => {
    setSound(withSound);
    toggle();
  };
  /** Move the playhead (scrubber, ±10s, chapters); the voice follows. */
  const seek = (ms: number) => {
    const to = Math.min(TOTAL - 1, Math.max(0, ms));
    setStarted(true);
    setT(to);
    tRef.current = to;
    if (audio.current) audio.current.currentTime = Math.min(to / 1000, AUDIO_END);
  };
  const jump = (i: number) => {
    seek(START[i]);
    setPlaying(true);
  };
  // A text row below asked to play from a chapter: bring the player into view and play with sound
  // (the click that sent it counts as the user's go-ahead for audio).
  const jumpRef = useRef(jump);
  useEffect(() => {
    jumpRef.current = jump;
  });
  useEffect(() => {
    const onPlay = (e: Event) => {
      const i = CHAPTERS.findIndex((c) => c.tab === (e as CustomEvent<string>).detail);
      if (i < 0) return;
      box.current?.scrollIntoView({ behavior: "smooth", block: "center" });
      setSound(true);
      jumpRef.current(i);
    };
    window.addEventListener("hp-tour-play", onPlay);
    return () => window.removeEventListener("hp-tour-play", onPlay);
  }, []);

  const done = t >= TOTAL;
  // Before the first play, show chapter 1 fully drawn as the poster.
  const ch = started ? Math.min(CHAPTERS.length - 1, chapterAt(t)) : 0;
  const lt = started ? (done ? DUR[ch] : t - START[ch]) : DUR[0];
  useEffect(() => {
    tRef.current = t;
  }, [t]);

  // Voice: one continuous take. Start it from wherever the clock is; it only
  // loads once someone turns sound on.
  useEffect(() => {
    if (!playing || !sound || !started) {
      audio.current?.pause();
      return;
    }
    const a = (audio.current ??= new Audio("/tour/tour.mp3"));
    const at = tRef.current / 1000;
    if (at >= AUDIO_END) return;
    if (Math.abs(a.currentTime - at) > 0.3) a.currentTime = at;
    a.play().catch(() => setSound(false));
    return () => a.pause();
  }, [playing, sound, started]);
  const { Scene } = CHAPTERS[ch];
  // The phrase she's saying right now (the first one on the poster).
  const cue = started ? Math.max(0, CAPS.findLastIndex(([at]) => t >= at * 1000)) : 0;

  return (
    <div className={`tp${playing ? " is-playing" : ""}`} ref={box}>
      <div className="tp-stage">
        <div className="tp-scene" key={ch}>
          <Scene lt={lt} />
        </div>
        <div className="tp-capbox" aria-live="off">
          {cc && (
            <p className="tp-cap" key={cue}>
              {CAPS[cue][1]}
            </p>
          )}
        </div>
        {!playing && (
          <div className={`tp-big${started ? " is-paused" : ""}`}>
            <button className="tp-big-go" onClick={() => start(started ? sound : true)} aria-label={done ? "Replay the tour" : "Play the tour"}>
              <span aria-hidden>{done ? "↺" : "▶"}</span>
              {done ? "Watch again" : started ? "Resume" : `Watch with sound · ${mmss(TOTAL)}`}
            </button>
            {!started && (
              <button className="tp-big-mute" onClick={() => start(false)}>
                or watch muted
              </button>
            )}
          </div>
        )}
      </div>

      <input
        className="tp-scrub"
        type="range"
        min={0}
        max={TOTAL}
        step={100}
        value={t}
        onChange={(e) => seek(Number(e.target.value))}
        style={{ ["--p" as string]: `${(t / TOTAL) * 100}%` }}
        aria-label="Seek"
        aria-valuetext={`${mmss(t)} of ${mmss(TOTAL)}`}
      />
      <div className="tp-bar">
        <button className="tp-play" onClick={toggle} aria-label={playing ? "Pause" : "Play"}>
          {playing ? "❚❚" : done ? "↺" : "▶"}
        </button>
        <nav className="tp-tabs" aria-label="Tour chapters">
          {CHAPTERS.map((c, i) => (
            <button key={c.tab} onClick={() => jump(i)} aria-current={started && i === ch ? "step" : undefined}>
              {c.tab}
            </button>
          ))}
        </nav>
        <button className="tp-sound" onClick={toggleCc} aria-pressed={cc} aria-label={cc ? "Hide captions" : "Show captions"}>
          CC
        </button>
        <button className="tp-sound" onClick={() => setSound((v) => !v)} aria-pressed={sound} aria-label={sound ? "Mute" : "Turn sound on"}>
          {sound ? "Sound on" : "Muted"}
        </button>
        <span className="tp-time num">
          {mmss(t)} / {mmss(TOTAL)}
        </span>
      </div>
    </div>
  );
}

/** true once the chapter clock passes `ms`. */
const on = (lt: number, ms: number) => (lt >= ms ? " on" : "");

/* ── Scenes ── */

function Hello({ lt }: { lt: number }) {
  return (
    <div className="ts-end">
      <small className={`ts-note${on(lt, 200)}`}>Welcome to</small>
      <strong className={`ts-end-word${on(lt, 500)}`}>HedgePredict</strong>
      <p className={`ts-hello${on(lt, 1400)}`}>Your prediction market assistant.</p>
    </div>
  );
}

/** Beats follow the voice: payout on "Each share pays", profit on "Buy at", the price on "The price is also". */
function Prices({ lt }: SceneProps) {
  return (
    <div className="ts-card ts-market">
      <span className="ts-k">Polymarket · a yes-or-no question</span>
      <b className="ts-q">Will Kentucky beat South Carolina?</b>
      <p className={`ts-pay${on(lt, beat("pay"))}`}>
        Right <span>→</span> <b>$1.00</b> a share · Wrong <span>→</span> <b>$0</b>
      </p>
      <p className={`ts-pay${on(lt, beat("profit"))}`}>
        Buy at 43¢, win <span>→</span> <b>$1.00</b> back = your 43¢ + <b className="is-wager">57¢ profit</b>
      </p>
      <div className="ts-prices">
        <div className={`ts-price${on(lt, beat("pct"))}`}>
          <small>Kentucky</small>
          <strong>43¢</strong>
          <em className={`ts-note${on(lt, beat("pct") + 900)}`}>≈ 43% chance</em>
        </div>
        <div className="ts-price is-dim">
          <small>South Carolina</small>
          <strong>58¢</strong>
        </div>
      </div>
    </div>
  );
}

/** The switch flips on "plus one hundred thirty-three"; the note follows it on screen only. */
function Odds({ lt }: SceneProps) {
  const us = lt >= beat("us");
  const sides = [
    { k: "Kentucky", c: "43¢", a: "+133" },
    { k: "South Carolina", c: "58¢", a: "-138" },
  ];
  return (
    <div className="ts-card ts-odds">
      <div className="ts-odds-top">
        <span className="ts-k">Kentucky vs. South Carolina</span>
        <span className="ts-switch" aria-hidden>
          <i className={us ? "" : "is-on"}>¢</i>
          <i className={us ? "is-on" : ""}>US</i>
        </span>
      </div>
      <div className="ts-prices">
        {sides.map((x, i) => (
          <div key={x.k} className={`ts-price${i ? " is-dim" : ""}`}>
            <small>{x.k}</small>
            <strong className="ts-flip">
              <span className={us ? "is-out" : ""}>{x.c}</span>
              <span className={us ? "" : "is-out"}>{x.a}</span>
            </strong>
          </div>
        ))}
      </div>
      <p className={`ts-pay${on(lt, beat("us") + 1600)}`}>Sportsbook lines can differ a little. Use it as a guide.</p>
    </div>
  );
}

const ROWS: { q: string; call: "Wager" | "Lean" | "Skip"; px: string }[] = [
  { q: "Kentucky vs. South Carolina", call: "Wager", px: "43¢" },
  { q: "Yankees vs. Rays", call: "Skip", px: "55¢" },
  { q: "Bitcoin above $90k on Friday?", call: "Lean", px: "31¢" },
  { q: "Fed cuts rates in December?", call: "Skip", px: "62¢" },
  { q: "Chiefs vs. Raiders", call: "Lean", px: "66¢" },
];

function Board({ lt }: { lt: number }) {
  return (
    <div className="ts-board">
      {ROWS.map((r, i) => (
        <div key={r.q} className={`ts-row${on(lt, 200 + i * 220)}`}>
          <span className="ts-row-q">{r.q}</span>
          <span className={`ts-call is-${r.call.toLowerCase()}${on(lt, 2200 + i * 380)}`}>{r.call}</span>
          <span className="ts-row-px num">{r.px}</span>
        </div>
      ))}
    </div>
  );
}

function Calls({ lt }: { lt: number }) {
  const calls = [
    { w: "Wager", m: "HedgePredict likes Kentucky at this price.", c: "wager" },
    { w: "Lean", m: "Bitcoin looks a little cheap. A softer recommendation.", c: "lean" },
    { w: "Skip", m: "Priced about right. No recommendation.", c: "skip" },
  ];
  return (
    <div className="ts-calls">
      {calls.map((x, i) => (
        <div key={x.w} className={`ts-callcol is-${x.c}${on(lt, 300 + i * 900)}`}>
          <strong>{x.w}</strong>
          <p>{x.m}</p>
        </div>
      ))}
    </div>
  );
}

function Sure({ lt }: { lt: number }) {
  const k = Math.min(1, Math.max(0, (lt - 500) / 1800));
  const n = Math.round(66 * (1 - Math.pow(1 - k, 3)));
  return (
    <div className="ts-card ts-sure">
      <span className="ts-k">Kentucky vs. South Carolina</span>
      <strong className="ts-call-big is-wager">Wager</strong>
      <p className="ts-sure-line">
        <b className="num">{n}%</b> sure Kentucky is too cheap
      </p>
      <span className="ts-bar" aria-hidden>
        <i style={{ transform: `scaleX(${n / 100})` }} />
      </span>
      <p className={`ts-conf${on(lt, 2800)}`}>Medium confidence</p>
    </div>
  );
}

function Hedge({ lt }: { lt: number }) {
  const locked = lt >= 2600;
  const outs = [
    { k: "If Yes wins", before: 75, after: 12.5 },
    { k: "If No wins", before: -50, after: 12.5 },
  ];
  return (
    <div className="ts-card ts-hedge">
      <span className="ts-k ts-lab">Hedge Lab</span>
      <p className="ts-hedge-head">
        You hold <b>$50 on Yes at 40¢</b>.{" "}
        <span className={`ts-note${on(lt, 1400)}`}>
          Put <b>$62.50 on No</b> at 50¢:
        </span>
      </p>
      {outs.map((o) => {
        const v = locked ? o.after : o.before;
        return (
          <div key={o.k} className="ts-out">
            <small>{o.k}</small>
            <span className="ts-out-track" aria-hidden>
              <i className={v < 0 ? "is-neg" : ""} style={{ width: `${(Math.abs(v) / 75) * 50}%`, [v < 0 ? "right" : "left"]: "50%" }} />
            </span>
            <b className={`num${v < 0 ? " is-neg" : ""}`}>{`${v < 0 ? "-" : "+"}$${Math.abs(v).toFixed(2)}`}</b>
          </div>
        );
      })}
      <p className={`ts-locked${on(lt, 3000)}`}>Locked: +$12.50 either way.</p>
    </div>
  );
}

/** The email lands on "Sign up for The Daily". */
function Daily({ lt }: { lt: number }) {
  const m = beat("mail");
  return (
    <div className={`ts-card ts-mail${on(lt, m)}`}>
      <div className="ts-mail-head">
        <span className="ts-ava" aria-hidden>H</span>
        <div>
          <b>HedgePredict Daily</b>
          <small>to me · 8:00 AM</small>
        </div>
      </div>
      <b className="ts-mail-subj">Today&apos;s pick: Kentucky at 43¢</b>
      <div className={`ts-mail-pick${on(lt, m + 1300)}`}>
        <span className="ts-call is-wager on">Wager</span>
        <span>Kentucky vs. South Carolina · 66% sure it&apos;s too cheap</span>
      </div>
      <p className={`ts-mail-more${on(lt, m + 2500)}`}>Plus the board, what resolves today, and the biggest movers.</p>
    </div>
  );
}

const FOUND = [
  { q: "Fed cuts rates in December?", px: "62¢" },
  { q: "Fed cuts rates in January?", px: "41¢" },
  { q: "Fed hikes rates in 2027?", px: "9¢" },
];

/** Two beats: the search bar finds any market ("Search all…"), then Ask HedgePredict ("or ask…"). */
function SearchAsk({ lt }: SceneProps) {
  const srch = beat("srch");
  const asked = beat("askhp");
  if (lt < asked) {
    // Typed while she sets it up; the results land on "Search all of Polymarket".
    const term = "fed rates";
    const typed = term.slice(0, Math.max(0, Math.floor((lt - 500) / 60)));
    const shown = srch;
    return (
      <div className="ts-card ts-search">
        <span className="ts-k">Search all of Polymarket</span>
        <p className="ts-search-bar">{typed || <i className="ts-caret" aria-hidden />}</p>
        {FOUND.map((r, i) => (
          <div key={r.q} className={`ts-row${on(lt, shown + i * 160)}`}>
            <span className="ts-row-q">{r.q}</span>
            <span className="ts-row-px num">{r.px}</span>
          </div>
        ))}
      </div>
    );
  }
  const ask = "What's the call on a December cut?";
  const typed = ask.slice(0, Math.max(0, Math.floor((lt - asked) / 22)));
  return (
    <div className="ts-card ts-chat">
      <span className="ts-k">Ask HedgePredict</span>
      <p className="ts-bub is-you">{typed || " "}</p>
      <p className={`ts-bub is-ai${on(lt, asked + 950)}`}>
        <b className="is-skip">Skip.</b> At 62¢ the price looks about right. HedgePredict is 61% sure it&apos;s fair, so there&apos;s no edge to chase here.
      </p>
    </div>
  );
}

const MCP_LINK = "hedgepredict.co/api/mcp";

/**
 * The link pastes in on "connect HedgePredict", the apps it works in appear on
 * "any AI tool", the box lights again on "Paste one link", then the chat on "then just ask".
 */
function Ai({ lt }: { lt: number }) {
  const conn = beat("conn");
  const asked = beat("ask");
  if (lt < asked) {
    const pasted = lt >= conn;
    const lit = pasted && (lt < conn + 900 || (lt >= beat("paste") && lt < beat("paste") + 900));
    return (
      <div className="ts-card ts-connect">
        <span className="ts-k">Connect your AI</span>
        <p className={`ts-connect-url${lit ? " is-pasted" : ""}`}>
          {pasted ? MCP_LINK : <i className="ts-caret" aria-hidden />}
        </p>
        <p className={`ts-connect-ok${on(lt, conn + 700)}`}>Connected to HedgePredict</p>
        <p className={`ts-pay${on(lt, beat("apps"))}`}>Works in Claude · ChatGPT · Cursor · Gemini · any MCP app</p>
      </div>
    );
  }
  const ask = "Any good plays tonight?";
  const typed = ask.slice(0, Math.max(0, Math.floor((lt - asked) / 24)));
  return (
    <div className="ts-card ts-chat">
      <span className="ts-k">Connect your AI</span>
      <p className="ts-bub is-you">{typed || " "}</p>
      <p className={`ts-bub is-ai${on(lt, asked + 650)}`}>
        HedgePredict&apos;s recommendation: <b className="is-wager">Kentucky at 43¢ (Wager).</b> It&apos;s 66% sure that price is too cheap. Everything else on tonight&apos;s board looks priced about
        right.
      </p>
    </div>
  );
}

function End({ lt }: { lt: number }) {
  return (
    <div className="ts-end">
      <strong className={`ts-end-word${on(lt, 200)}`}>HedgePredict</strong>
      <p className={`ts-end-3${on(lt, 1000)}`}>
        <span className="is-wager">Wager.</span> <span className="is-lean">Lean.</span> <span className="is-skip">Skip.</span>
      </p>
      <small className={`ts-note${on(lt, 2200)}`}>Decision support, not financial advice. We never place trades.</small>
    </div>
  );
}
